baseURL = "https://example.org/"
languageCode = "en-us"
title = "My Obsidian Site"
theme = "ananke" # השם הנכון של ערכת הנושא

[markup]
  # הגדרה זו חיונית כדי למנוע שגיאות קישורים ורינדור תקין של Markdown/HTML ב-Obsidian
  [markup.goldmark.renderer]
    unsafe = true