baseURL = "https://example.org/"
languageCode = "en-us"
title = "My Obsidian Site"
theme = "ananke" # <--- השם המקורי והנכון

# הגדרות עיבוד משאבים (חובה לתבנית)
[markup]
  [markup.goldmark.renderer]
    unsafe = true